version: '3'
services:
  web:
    image: nginx
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=wordpresslogin
      - MYSQL_USER=wordpress-dev-user
      - MYSQL_PASSWORD=passwordfordevelopment
      - MYSQL_DATABASE=wordpress-development-db


